# project/content/categories.py
# A clean, simple structure. The dynamic hook generator removes the need for tagging.

CATEGORIES = {
    "Work Power": ["Handling disrespect calmly", "Silent authority responses", "Power without escalation", "Neutral shutdowns", "Public pressure control", "Private correction tactics", "Framing dominance", "Emotional non-reaction", "Status recovery", "Boundary resets", "Meeting control", "Interrupt handling", "Passive aggression shutdown", "Power pauses", "Voice neutrality", "Eye contact control", "Respect enforcement", "Subtle authority signals", "Composure under attack", "Final word tactics"],
    "Career Authority": ["Securing high-status projects", "Navigating promotions", "Managing upward perception", "Building silent influence", "Becoming indispensable", "Rejecting low-value tasks", "Owning your expertise", "Controlling your narrative", "Escaping career plateaus", "Setting long-term frames", "Forging key alliances", "Demonstrating strategic value", "Project ownership tactics", "Avoiding grunt work", "Mentorship power dynamics", "Competency framing", "Unspoken leadership signals", "Salary negotiation frames", "Refusing scope creep", "Exit strategy power"],
    "Office Presence": ["Entering rooms with impact", "Mastering the office walk", "The art of being still", "Occupying space correctly", "Projecting calm confidence", "Your desk as a power base", "Elevator presence", "Non-verbal status cues", "Being seen as essential", "Controlled visibility", "Navigating open offices", "Posture and authority", "Minimalist communication", "Managing your energy", "The look of focus", "Unflappable demeanor", "Gravitas in meetings", "Intentional movement", "The illusion of time", "Being unforgettable"],
    "Leadership Control": ["Delegating for power", "Setting unbreakable standards", "The one-minute correction", "Issuing clear directives", "Maintaining team focus", "Eliminating groupthink", "Handling underperformers", "Fostering internal competition", "The power of decisiveness", "Shielding your team", "Absorbing pressure", "Rewarding loyalty", "Creating a performance culture", "Implied consequences", "Decisive action", "Limiting your access", "Strategic praise", "Unemotional feedback", "The final decision", "Authority through consistency"],
    "Negotiation Psychology": ["Anchoring the first offer", "The power of walking away", "Using silence strategically", "Making them justify", "Controlling the timeline", "Never splitting the difference", "Framing the value", "Creating scarcity", "The illusion of concession", "Emotional detachment", "Information control", "Letting them feel they won", "Revealing weakness strategically", "Reading hidden needs", "The no-flinch rule", "Countering pressure tactics", "Shifting the power balance", "Uncovering their constraints", "The final offer frame", "Post-negotiation control"],
    "Social Dominance": ["Controlling conversation flow", "Mastering group dynamics", "The art of the subtle roast", "Using humor as a weapon", "Being the point of reference", "Granting and revoking attention", "Frame control in groups", "Disqualifying challengers", "Creating an inner circle", "Projecting social abundance", "The subtle power of touch", "Eye contact triangulation", "Unimpressed responses", "Leading group decisions", "Setting the social mood", "Handling social climbers", "Ignoring low-status signals", "The power of agreement frames", "Amused mastery", "Being the prize"],
    "Boundary Enforcement": ["The one-word 'No'", "The consequence statement", "Shutting down intrusive questions", "Protecting your time", "The professional disengage", "Responding to overfamiliarity", "The broken record technique", "Setting communication rules", "The cost of access", "Rejecting unwanted requests", "Enforcing your availability", "Calmly stating your limits", "The non-negotiable frame", "Preventing future violations", "Escalation without emotion", "The silent treatment", "Financial boundary setting", "Emotional boundary setting", "Holding the line", "Reclaiming your space"],
    "Verbal Defense": ["The reframe tactic", "The 'What do you mean' defense", "Agree and amplify", "Turning questions back", "The label and dismiss", "Exposing hidden intent", "The neutral observation", "Deflecting insults calmly", "Word-for-word repetition", "The fogging technique", "Shifting from content to intent", "The 'I disagree' shutdown", "Deconstructing assumptions", "One-word answers", "The bored response", "The direct challenge", "Asking for clarification", "The pattern interrupt", "The closing statement", "Disarming with logic"],
    "Respect Management": ["Correcting your name pronunciation", "Resetting after disrespect", "Setting the tone early", "The respect demand", "Responding to condescension", "Handling public challenges", "Not laughing at bad jokes", "Projecting self-respect", "The value of being serious", "Demanding professional courtesy", "Ignoring attempts to belittle", "The power of your title", "Letting silence demand respect", "The expectation frame", "Your time is valuable", "The cost of disrespect", "Slowing down the pace", "Never over-explaining", "Responding to unwanted nicknames", "The standard of treatment"],
    "Conflict Control": ["De-escalation through framing", "Lowering your voice", "The common ground technique", "Separating person from problem", "The pause before responding", "Stating facts not feelings", "Avoiding blame language", "The 'solution focus' pivot", "Controlling the environment", "Refusing to argue", "The strategic exit", "Dictating the next step", "Setting terms for discussion", "Acknowledging without agreeing", "The final word protocol", "Mirroring then shifting tone", "Disarming emotional outbursts", "The logical frame", "Taking it offline", "Decisive resolution"],
    "Status Awareness": ["Reading unspoken hierarchies", "Identifying the true decision-maker", "Recognizing status signals", "Avoiding low-status behaviors", "Understanding social capital", "Aligning with power players", "Low vs high-status language", "Navigating status mismatches", "Projecting higher status", "The politics of seating", "Who yields to whom", "Gift giving politics", "Mimicking high-status patterns", "Recognizing deference signals", "The power of being underestimated", "Strategic self-deprecation", "Status in communication", "Ignoring status challenges", "The information gatekeeper", "Code-switching effectively"],
    "Professional Assertiveness": ["Stating needs without apology", "Saying no to your boss", "Taking credit for your work", "Disagreeing in meetings", "Voicing unpopular opinions", "Pitching your ideas", "Asking for a raise", "Pushing back on deadlines", "Defending your team", "The direct request", "The proactive solution frame", "Interrupting to correct", "Setting the meeting agenda", "Questioning authority respectfully", "The 'I need' statement", "Following up relentlessly", "Preventing idea theft", "Documenting everything", "The assertive refusal", "Escalating with evidence"],
    "Emotional Regulation": ["The tactical pause", "Detaching from outcomes", "Neutralizing trigger words", "The emotion-to-logic shift", "Maintaining a neutral face", "Controlling your breathing", "Lowering your heart rate", "The 'observer self' technique", "Responding not reacting", "The power of a monotone voice", "Processing anger later", "Avoiding emotional contagion", "Projecting unshakable calm", "The mental reframe", "Recognizing emotional bait", "Disengaging from provocations", "The 'so what' mentality", "Delaying your response", "Emotional energy conservation", "Indifference as a weapon"],
    "Psychological Leverage": ["The principle of reciprocity", "Creating a debt", "The power of consistency", "The 'foot-in-the-door' technique", "The 'door-in-the-face' technique", "The scarcity principle", "Leveraging social proof", "The authority bias", "The liking principle", "Framing for loss aversion", "The endowment effect", "Using curiosity gaps", "The power of labels", "Creating a shared enemy", "The pattern interrupt", "Anchoring expectations", "The contrast principle", "The 'because' justification", "Future pacing", "The illusion of choice"],
    "Decision Authority": ["The decisive statement", "Making the call under pressure", "Taking ownership of outcomes", "Simplifying complex choices", "The 'good enough' decision", "Avoiding analysis paralysis", "Gathering just enough data", "The framework for delegation", "Overruling consensus", "The no-debate declaration", "Setting decision deadlines", "Communicating the final choice", "The one-sentence justification", "Reversible vs irreversible", "Trusting your intuition", "The cost of indecision", "The executive decision", "Cutting off discussion", "Moving to implementation", "Defending your decision"],
    "Reputation Control": ["Crafting your public narrative", "Shutting down gossip", "The strategic information leak", "Building a brand of reliability", "Correcting misinformation fast", "The power of a clean record", "Projecting consistency", "Being known for one thing", "The association principle", "Managing your digital footprint", "The 'no comment' strategy", "The apology as a power move", "Building social proof", "Showcasing wins subtly", "Handling negative feedback", "Creating a personal monopoly", "The power of testimonials", "The quiet professional", "Becoming the go-to person", "The legacy project"],
    "Strategic Communication": ["Saying less to mean more", "The power of the unsaid", "The one-sentence email", "Using questions to lead", "The pre-suasion frame", "Priming the audience", "Message discipline", "The BLUF principle", "The power of ambiguity", "The strategic pause", "Communicating intent not detail", "The back-channel conversation", "Public vs private message", "Using silence to get answers", "The echo technique", "Framing vs spinning", "The controlled narrative", "The final word", "The power of understatement", "The indirect command"],
    "Influence Mechanics": ["The value-first approach", "Building a coalition", "The art of the small ask", "The consistency trap", "The power of a shared identity", "The charisma pattern", "The expert frame", "The passion frame", "Leveraging weak ties", "The demonstration of value", "Making others feel smart", "The transfer of ownership", "The co-creation frame", "The inevitability frame", "The social proof cascade", "The challenge frame", "The storyteller's advantage", "The vision frame", "The secret knowledge frame", "The trusted advisor role"],
    "Personal Power": ["The power of routine", "The discipline of self-care", "The unshakable core", "The 'no' that builds respect", "The internal locus of control", "The power of your word", "The principle of non-reaction", "The ownership of your mistakes", "The art of being self-contained", "The value of solitude", "The zero-neediness frame", "The power of your own validation", "The long-term perspective", "The anti-fragile mindset", "The stoic response to chaos", "The commitment to your standards", "The power of walking away", "The decisive action habit", "The reputation for finishing", "The unbreakable self-concept"],
    "Human Behavior Decoding": ["Reading micro-expressions", "Spotting verbal tells", "Understanding proxemics", "Identifying hidden motivations", "The power of baseline behavior", "Decoding body language clusters", "Recognizing deflection tactics", "Uncovering the real question", "The lie detection framework", "Listening for what isn't said", "Identifying emotional shifts", "The power of mirroring", "Recognizing ego-driven behavior", "Understanding cognitive biases", "The status-seeking drive", "The need for significance", "The pain-pleasure principle", "The consistency principle in others", "Reading vocal tonality", "The desire for certainty"]
}