# project/content/seo.py

# This file contains the templates and assets for the Facebook Reels post.
# It follows the "Short. Clean. Calm." philosophy.

# --- Caption Template ---
# This caption is intentionally general to fit any video generated by the system.
# It reinforces the brand's core message of calm authority.

CAPTION_TEMPLATE = """
Most people lose control because they react.
This shows you how to stay calm and keep your authority.

Follow for more psychological control tactics.
"""


# --- Hashtag Rotation Strategy ---
# To avoid spam signals and keep content fresh, we rotate through curated groups of hashtags.
# The posting script will randomly select one of these lists for each video.

HASHTAG_GROUPS = [
    ["#psychology", "#authority", "#workpower", "#leadership"],
    ["#socialskills", "#confidence", "#selfcontrol", "#respect"],
    ["#communication", "#assertiveness", "#mentalmodels", "#power"],
    ["#psychology", "#selfcontrol", " #leadership", "#confidence"],
    ["#authority", "#respect", "#workpower", "#socialskills"],
]

# Note: The whitespace in the caption and the structure of the hashtag groups
# are intentional for clean formatting on Facebook.